apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: webapp-production
  name: web-frontend
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - image: frodood/webapp:BUILD_ID
          imagePullPolicy: Always
          name: web-frontend
          ports:
            - containerPort: 80
