apiVersion: v1
kind: Service
metadata:
  namespace: webapp-integration
  name: web-frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-frontend
