---
- name: Installing Docker, kubectl, Jenkins
  hosts: utility-server
  gather_facts: false
  become: true
  vars:
    certificate-authority-data: ""
    cluster_name: ""
    client-certificate-data: ""
    client-key-data: ""
    password: ""

  tasks:
  - import_role:
      name: docker
  - import_role:
      name: kubectl
  - import_role:
      name: jenkins
