---
- name: Installing Docker, kubectl, Jenkins
  hosts: utility-server
  gather_facts: false
  become: true

  tasks:
  - import_role:
      name: docker
  - import_role:
      name: kubectl
  - import_role:
      name: jenkins
