---
- name: Installing Docker, kubectl, Jenkins
  hosts: app-server
  gather_facts: false
  become: true

  vars_prompt:
    - name: certificate_authority_data
      prompt: "Enter cert authority data"
    - name: cluster_name
      prompt: "Enter cluster name"
    - name: client_certificate_data
      prompt: "Enter client cert authority data"
    - name: client_key_data
      prompt: "Enter client key data"
    - name: password
      prompt: "Enter password"
    - name: username
      prompt: "Enter username"


  tasks:
  - import_role:
      name: docker
  - import_role:
      name: kubectl
  - import_role:
      name: jenkins
