
---
- name: Install Prometheus
  hosts: app-server
  gather_facts: false
  become: true
  vars:
    prometheus_link: https://github.com/prometheus/prometheus/releases/download/v1.6.2/prometheus-1.6.2.linux-amd64.tar.gz
    prometheus_dir: /opt/prometheus
    systemd_dir: /lib/systemd/system
    scrape: 5s
    evaluation: 5s
  vars_prompt:
    - name: elb
      prompt: "Enter ELB DNS"
  
  tasks:
  - import_role:
      name: prometheus
